//
//  appLibCommon-Bridging-Header.h
//  ScriptureApp
//
//  Created by David Moore on 5/6/15.
//  Copyright (c) 2015 David Moore. All rights reserved.
//

#ifndef ScriptureApp_appLibCommon_Bridging_Header_h
#define ScriptureApp_appLibCommon_Bridging_Header_h
#import "IOSClass.h"
#import "IOSArray.h"
#import "IOSPrimitiveArray.h"
#import "J2ObjC_source.h"
#import "J2ObjC_common.h"
#import "java/io/BufferedReader.h"
#import "java/io/ByteArrayInputStream.h"
#import "java/io/ByteArrayOutputStream.h"
#import "java/io/FileInputStream.h"
#import "java/io/IOException.h"
#import "java/io/InputStream.h"
#import "java/io/InputStreamReader.h"
#import "java/util/ArrayList.h"
#import "java/util/List.h"
#import "java/util/ListIterator.h"
#import "java/util/zip/GZIPInputStream.h"
#import "java/io/File.h"
#import "java/io/InputStream.h"
#import "java/lang/StringBuilder.h"
//#import "java/util/Collection.h"
//#import "java/util/List.h"
#import "JavaObject.h"
#import "J2ObjC_header.h"
#import "NSObject+JavaObject.h"
#import "AppConfig.h"
#import "AppLibrary.h"
#import "AudioInfo.h"
#import "Book.h"
#import "BookCollection.h"
#import "c.h"
#import "Chapter.h"
#import "ColorDefs.h"
#import "CommonFeatureName.h"
#import "CommonStringId.h"
#import "Config.h"
#import "ConfigParser.h"
#import "DisplayWriter.h"
#import "Element.h"
#import "Elements.h"
#import "Encryption.h"
#import "FactoryCommon.h"
#import "Features.h"
#import "FileManagerCommon.h"
#import "FileManagerIOS.h"
#import "Links.h"
#import "PopupHandler.h"
#import "PropertyName.h"
#import "Reference.h"
#import "ScriptureConfigHandler.h"
#import "ScriptureFeatureName.h"
#import "ScriptureStringId.h"  // From ScriptureString.java
#import "SearchHandler.h"
#import "SearchResult.h"
#import "StringManager.h"
#import "StringUtils.h"
#import "StyleName.h"
#import "XMLParser.h"
#import "IOSFactory.h"
#import "ScriptureFactoryIOS.h"

#endif
