//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/david/Source/GitHub/app-builders/source/common/app-lib-common/src/org/sil/app/lib/common/utils/BaseEncryption.java
//


#line 1 "/Users/david/Source/GitHub/app-builders/source/common/app-lib-common/src/org/sil/app/lib/common/utils/BaseEncryption.java"

#include "BaseEncryption.h"
#include "J2ObjC_source.h"

@interface ALCUBaseEncryption () {
 @public
  NSString *charsetName_;
  NSString *algorithm_;
  NSString *mKey_;
}

@end

J2OBJC_FIELD_SETTER(ALCUBaseEncryption, charsetName_, NSString *)
J2OBJC_FIELD_SETTER(ALCUBaseEncryption, algorithm_, NSString *)
J2OBJC_FIELD_SETTER(ALCUBaseEncryption, mKey_, NSString *)


#line 10
@implementation ALCUBaseEncryption


#line 17
- (instancetype)initWithNSString:(NSString *)key {
  ALCUBaseEncryption_initWithNSString_(self, key);
  return self;
}


#line 21
- (NSString *)getCharsetName {
  return charsetName_;
}

- (void)setCharsetNameWithNSString:(NSString *)charsetName {
  ALCUBaseEncryption_set_charsetName_(self, charsetName);
}

- (NSString *)getAlgorithm {
  return algorithm_;
}

- (void)setAlgorithmWithNSString:(NSString *)algorithm {
  ALCUBaseEncryption_set_algorithm_(self, algorithm);
}

- (NSString *)encryptWithNSString:(NSString *)data {
  
#line 39
  return nil;
}


#line 53
- (NSString *)decryptWithNSString:(NSString *)data {
  
#line 55
  return nil;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "BaseEncryption", NULL, 0x1, NULL, NULL },
    { "getCharsetName", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "setCharsetNameWithNSString:", "setCharsetName", "V", 0x1, NULL, NULL },
    { "getAlgorithm", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "setAlgorithmWithNSString:", "setAlgorithm", "V", 0x1, NULL, NULL },
    { "encryptWithNSString:", "encrypt", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "decryptWithNSString:", "decrypt", "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "charsetName_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL,  },
    { "algorithm_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL,  },
    { "mKey_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ALCUBaseEncryption = { 2, "BaseEncryption", "org.sil.app.lib.common.utils", NULL, 0x401, 7, methods, 3, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ALCUBaseEncryption;
}

@end


#line 17
void ALCUBaseEncryption_initWithNSString_(ALCUBaseEncryption *self, NSString *key) {
  NSObject_init(self);
  ALCUBaseEncryption_set_charsetName_(self,
#line 12
  @"UTF8");
  ALCUBaseEncryption_set_algorithm_(self, @"DES");
  
#line 18
  ALCUBaseEncryption_set_mKey_(self, key);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ALCUBaseEncryption)
