//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/david/Source/GitHub/app-builders/source/common/app-lib-common/src/org/sil/app/lib/common/utils/BaseEncryption.java
//

#ifndef _ALCUBaseEncryption_H_
#define _ALCUBaseEncryption_H_

#include "J2ObjC_header.h"

@interface ALCUBaseEncryption : NSObject

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)key;

- (NSString *)decryptWithNSString:(NSString *)data;

- (NSString *)encryptWithNSString:(NSString *)data;

- (NSString *)getAlgorithm;

- (NSString *)getCharsetName;

- (void)setAlgorithmWithNSString:(NSString *)algorithm;

- (void)setCharsetNameWithNSString:(NSString *)charsetName;

@end

J2OBJC_EMPTY_STATIC_INIT(ALCUBaseEncryption)

FOUNDATION_EXPORT void ALCUBaseEncryption_initWithNSString_(ALCUBaseEncryption *self, NSString *key);

J2OBJC_TYPE_LITERAL_HEADER(ALCUBaseEncryption)

typedef ALCUBaseEncryption OrgSilAppLibCommonUtilsBaseEncryption;

#endif // _ALCUBaseEncryption_H_
